### ISSUE TITLE
Feed.put with data yields weird results

### ISSUE THREAD

**Issue by Frando** [datrs/hypercore#107]
I was looking into coupling [hypercore-protocol-rs](https://github.com/Frando/hypercore-protocol-rs) to hypercore today a bit.

However, I was unable to put any data into a cloned hypercore. It seems the `put` method either has a bug or I did not understand how to use it correctly. I'll open a PR with a failing test.

**Comment by Frando** [comment]
See #108.

**Comment by bltavares** [comment]
@Frando Could you confirm that #110 and #111 fixed your issue, so we can close it?

**Comment by Frando** [comment]
Yes, this is fixed!
