### ISSUE TITLE
Read key pair from disk

### ISSUE THREAD

**Issue by soyuka** [datrs/hypercore#16]
Hi, I was reading the code and stumble onto the comment that said "@TODO Read key pair from disk". It doesn't look too hard to implement but I had a few questions:

- Do you already know from where you'd want to read the keys? My guess is that it should use the `Storage`, not sure!
- When the keypair doesn't exist (is generated), should it be written to disk (to the Storage?) as well?

Maybe that it's too early in the development to implement this though :).

Cheers.

**Comment by yoshuawuyts** [comment]
@soyuka hey! It'd be super cool if we could implement this! To answer your questions:
- yeah, let's store it in the storage
- when the keypair is generated it should indeed be written to the storage. If we use the memory backend, we'll just have an extra copy in memory - which is fine :sparkles:

You reckon this is something you would want to implement? :D

**Comment by soyuka** [comment]
Thanks for the answer!

> You reckon this is something you would want to implement? :D

Totally, at least try to :). Don't wait for me though if you need it and I'm not there yet (it'd have been a good exercise anyway!). Lot going on in my life currently, but if I can find some time I'd love to do this!
