### ISSUE TITLE
update random-access-*

### ISSUE THREAD

**Issue by FreddieRidell** [datrs/hypercore#73]
# Feature Request
## Summary
Update to the most recent versions of the `random-access-*` packages

## Motivation
+ Always good to keep up-to-date
+ `RandomAccess` trait contains `len` function, which seems to be required by #72

## Unresolved Questions
Is there some reason this hasn't been done already? Are these packages in a state of flux? Are there any known issues which make this hard/impossible

**Comment by yoshuawuyts** [comment]
> Are these packages in a state of flux?

The changes introduced in the random-access packages were mostly on substack's request. I see no harm in upgrading currently.

That said we're exploring how to make them available using async interfaces as that space moves along. But that shouldn't be a blocker for this.

**Comment by FreddieRidell** [comment]
resolved by https://github.com/datrs/hypercore/pull/77
